### ISSUE TITLE
Асуулт: translation library

### ISSUE THREAD

**Issue by bayartsogt-ya** [sharavsambuu/english-mongolian-nmt-dataset-augmentation#2]
Open source болгосонд баярлалаа!

Хоёр асуулт байна:
1. Орчуулга хийх үед [google-translate](https://translate.google.com)-ээс хэр ялгаатай байсан бэ? 
API-г нь ашиглаж байхад v2 болон v3 хоорондоо нэлээд зөрүүтэй санагдаж байсан. [Энэ library](https://textblob.readthedocs.io/en/dev/)-г ашиглаж орчуулсан гэсэн үг үү? ([Асуусан шалтгаан](https://github.com/sloria/TextBlob/issues/296#issuecomment-623118747))
2. Validated дата огт байхгүй бүгд орчуулагдсан дата гэсэн үг юм байна тэ?

**Comment by sharavsambuu** [comment]
1. Мэдэхгүй байна. Дотроо хувилбартай байсныг нь одоо л мэдлээ. Гэхдээ сүүлийн үед google translate-н орчуулгын чанар нилээн сайжирсан санагдаад байгаа. 
2. Алийг нь ч validate хийгээгүй.

**Comment by bayartsogt-ya** [comment]
@sharavsambuu 
Хурдан хариулсанд баярлалаа. 

Ер нь v2 оос бол нилээн сайжирсан санагдаад байгаа.
Гэхдээ бас GoogleTranslateAPI v3-ийг ашиглаж орчуулчихаад, яг сайттай нь тулгаж үзэхэд 90% орчим (батгүй тоо) таарч байсан.

Бүр яг гоё дататай больё гэвэл хос хэлтэй сайтуудаас crawl-даж таарах уу?
